# Generated by Django 2.0.1 on 2018-01-28 19:30

from django.db import migrations


def add_initial_data(apps, schema_editor):
    Country = apps.get_model('hr', 'Country')
    City = apps.get_model('hr', 'City')

    india = Country.objects.create(name='India')
    City.objects.create(name='Bengaluru', country=india)
    City.objects.create(name='Mumbai', country=india)
    City.objects.create(name='Chennai', country=india)
    City.objects.create(name='Hyderabad', country=india)
    City.objects.create(name='New Delhi', country=india)

    usa = Country.objects.create(name='United States')
    City.objects.create(name='New York', country=usa)
    City.objects.create(name='San Francisco', country=usa)
    City.objects.create(name='Los Angeles', country=usa)
    City.objects.create(name='Chicago', country=usa)
    City.objects.create(name='Seattle', country=usa)

    russia = Country.objects.create(name='Russia')
    City.objects.create(name='Moscow', country=russia)
    City.objects.create(name='Saint Petersburg', country=russia)
    City.objects.create(name='Yekaterinburg', country=russia)
    City.objects.create(name='Kazan', country=russia)
    City.objects.create(name='Krasnodar', country=russia)

    brazil = Country.objects.create(name='Brazil')
    City.objects.create(name='Sao Paulo', country=brazil)
    City.objects.create(name='Rio de Janeiro', country=brazil)
    City.objects.create(name='Belo Horizonte', country=brazil)
    City.objects.create(name='Curitiba', country=brazil)
    City.objects.create(name='Recife', country=brazil)

    uk = Country.objects.create(name='United Kingdom')
    City.objects.create(name='London', country=uk)
    City.objects.create(name='Huddersfield', country=uk)
    City.objects.create(name='Glasgow', country=uk)
    City.objects.create(name='Edinburgh', country=uk)
    City.objects.create(name='Cambridge', country=uk)


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_initial_data),
    ]
